/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedCrewRouteImport } from './routes/_authenticated/crew'
import { Route as AuthenticatedActivityIdRouteImport } from './routes/_authenticated/activity.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/_authenticated/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/_authenticated/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrewRoute = AuthenticatedCrewRouteImport.update({
  id: '/_authenticated/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityIdRoute = AuthenticatedActivityIdRouteImport.update({
  id: '/_authenticated/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/crew': typeof AuthenticatedCrewRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/': typeof AuthenticatedIndexRoute
  '/activity/$id': typeof AuthenticatedActivityIdRoute
}
export interface FileRoutesByTo {
  '/crew': typeof AuthenticatedCrewRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/': typeof AuthenticatedIndexRoute
  '/activity/$id': typeof AuthenticatedActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/crew': typeof AuthenticatedCrewRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/activity/$id': typeof AuthenticatedActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/crew' | '/plan' | '/stats' | '/' | '/activity/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/crew' | '/plan' | '/stats' | '/' | '/activity/$id'
  id:
    | '__root__'
    | '/_authenticated/crew'
    | '/_authenticated/plan'
    | '/_authenticated/stats'
    | '/_authenticated/'
    | '/_authenticated/activity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedCrewRoute: typeof AuthenticatedCrewRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedActivityIdRoute: typeof AuthenticatedActivityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crew': {
      id: '/_authenticated/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof AuthenticatedCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity/$id': {
      id: '/_authenticated/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof AuthenticatedActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedCrewRoute: AuthenticatedCrewRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedActivityIdRoute: AuthenticatedActivityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
